version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - todo-data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/todos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
      - ./backend/test_results:/app/test_results
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=testing
      - PYTHONUNBUFFERED=1
    depends_on:
      todo-api:
        condition: service_healthy

volumes:
  todo-data:

# Optional: Add a database service for production
# db:
#   image: postgres:13
#   environment:
#     POSTGRES_DB: todo_db
#     POSTGRES_USER: todo_user
#     POSTGRES_PASSWORD: todo_password
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"

# volumes:
#   postgres_data: 