version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
      platform: windows/amd64
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
      - todo-db:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/todos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      platform: windows/amd64
    environment:
      - FLASK_ENV=testing
      - PYTHONPATH=/app
      - KEPLOY_MODE=test
    volumes:
      - ./backend:/app
      - ./test_results:/app/test_results
    depends_on:
      todo-api:
        condition: service_healthy

  # Optional: Add a database service for production
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: todo_db
  #     POSTGRES_USER: todo_user
  #     POSTGRES_PASSWORD: todo_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  todo-db:
  # postgres_data: 